services:
  - type: web
    name: ahoum-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn config.wsgi:application --chdir backend
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
